export enum UserRole {
  ADMIN = 'ADMIN',
  STAFF = 'STAFF',
  MANAGER = 'MANAGER',
  DIRECTOR = 'DIRECTOR',
  PURCHASING = 'PURCHASING',
}

export enum ApproverType {
  MANAGER = 'MANAGER',
  DIRECTOR = 'DIRECTOR',
  PURCHASING = 'PURCHASING',
}

export enum RequestStatus {
  DRAFT = 'DRAFT',
  PENDING_MANAGER_APPROVAL = 'PENDING_MANAGER_APPROVAL',
  MANAGER_APPROVED = 'MANAGER_APPROVED',
  PENDING_DIRECTOR_APPROVAL = 'PENDING_DIRECTOR_APPROVAL',
  DIRECTOR_APPROVED = 'DIRECTOR_APPROVED',
  PENDING_PURCHASING_APPROVAL = 'PENDING_PURCHASING_APPROVAL',
  PURCHASING_APPROVED = 'PURCHASING_APPROVED',
  FULLY_APPROVED = 'FULLY_APPROVED',
  REJECTED = 'REJECTED',
  IN_PROCESS = 'IN_PROCESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  ON_HOLD = 'ON_HOLD',
}

export enum UrgencyLevel {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL',
}

export enum ApprovalStatus {
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  PENDING = 'PENDING',
}

export enum ItemCategory {
  FURNITURE = 'FURNITURE',
  ELECTRONICS = 'ELECTRONICS',
  OFFICE_SUPPLIES = 'OFFICE_SUPPLIES',
  COMPUTER_ACCESSORIES = 'COMPUTER_ACCESSORIES',
  MAINTENANCE = 'MAINTENANCE',
  OTHERS = 'OTHERS',
}

export enum NotificationType {
  REQUEST_CREATED = 'REQUEST_CREATED',
  PENDING_APPROVAL = 'PENDING_APPROVAL',
  REQUEST_APPROVED = 'REQUEST_APPROVED',
  REQUEST_REJECTED = 'REQUEST_REJECTED',
  FULLY_APPROVED = 'FULLY_APPROVED',
  IN_PROCESS = 'IN_PROCESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}
